-- Migration: 001_initial_schema.sql
-- VerbumDigital Web Radio - Initial Database Schema (MySQL)
-- Based on agreed schema with Svilen (Feb 2026)

-- ============================================
-- HARDWARE
-- ============================================
CREATE TABLE machines (
    id INT AUTO_INCREMENT PRIMARY KEY,
    machine_id VARCHAR(50) UNIQUE NOT NULL, -- es: "SMIX-12345"
    activated TINYINT(1) DEFAULT 0,
    activation_code VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- ============================================
-- CHURCHES
-- ============================================
CREATE TABLE churches (
    id INT AUTO_INCREMENT PRIMARY KEY,
    machine_id INT UNIQUE,
    name VARCHAR(200) NOT NULL,
    logo_url VARCHAR(500),
    address TEXT,
    streaming_active TINYINT(1) DEFAULT 0, -- Real-time status
    current_session_id INT, -- Populated later via FK
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_churches_machine FOREIGN KEY (machine_id) REFERENCES machines (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- ============================================
-- STREAMING CREDENTIALS (per church, permanent)
-- Generated by Admin on machine activation
-- Used by ST1 to identify the stream on Icecast
-- ============================================
CREATE TABLE streaming_credentials (
    id INT AUTO_INCREMENT PRIMARY KEY,
    church_id INT UNIQUE,
    stream_id VARCHAR(100) UNIQUE NOT NULL, -- Encoded into Icecast URL
    stream_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_credentials_church FOREIGN KEY (church_id) REFERENCES churches (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- ============================================
-- PRIESTS (can manage multiple churches)
-- ============================================
CREATE TABLE priests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- ============================================
-- PRIEST-CHURCH RELATIONSHIP (N:N)
-- ============================================
CREATE TABLE priest_churches (
    id INT AUTO_INCREMENT PRIMARY KEY,
    priest_id INT,
    church_id INT,
    role VARCHAR(20) DEFAULT 'owner', -- 'owner' or 'assistant'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_priest_church (priest_id, church_id),
    CONSTRAINT fk_pc_priest FOREIGN KEY (priest_id) REFERENCES priests (id) ON DELETE CASCADE,
    CONSTRAINT fk_pc_church FOREIGN KEY (church_id) REFERENCES churches (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- ============================================
-- USERS (fedeli)
-- ============================================
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- ============================================
-- USER SUBSCRIPTIONS (with notification prefs)
-- ============================================
CREATE TABLE user_subscriptions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    church_id INT,
    notifications_enabled TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_user_church (user_id, church_id),
    CONSTRAINT fk_sub_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_sub_church FOREIGN KEY (church_id) REFERENCES churches (id) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- ============================================
-- ADMINS (internal use)
-- ============================================
CREATE TABLE admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- ============================================
-- STREAMING SESSIONS (with statistics)
-- ============================================
CREATE TABLE streaming_sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    church_id INT,
    started_by_priest_id INT,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP NULL,
    duration_seconds INT,
    recording_url VARCHAR(500),
    max_listener_count INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_session_church FOREIGN KEY (church_id) REFERENCES churches (id),
    CONSTRAINT fk_session_priest FOREIGN KEY (started_by_priest_id) REFERENCES priests (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- Add FK from churches.current_session_id to streaming_sessions
ALTER TABLE churches
ADD CONSTRAINT fk_churches_current_session FOREIGN KEY (current_session_id) REFERENCES streaming_sessions (id);

-- ============================================
-- ACTIVE LISTENERS (real-time tracking)
-- Tracked via User PWA connections (as agreed with Svilen)
-- ============================================
CREATE TABLE active_listeners (
    id INT AUTO_INCREMENT PRIMARY KEY,
    session_id INT,
    user_id INT,
    connected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_heartbeat TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_listener_session FOREIGN KEY (session_id) REFERENCES streaming_sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_listener_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- ============================================
-- INDEXES for common queries
-- ============================================
CREATE INDEX idx_churches_streaming_active ON churches (streaming_active);

CREATE INDEX idx_churches_machine_id ON churches (machine_id);

CREATE INDEX idx_streaming_credentials_stream_id ON streaming_credentials (stream_id);

CREATE INDEX idx_priest_churches_priest_id ON priest_churches (priest_id);

CREATE INDEX idx_priest_churches_church_id ON priest_churches (church_id);

CREATE INDEX idx_user_subscriptions_user_id ON user_subscriptions (user_id);

CREATE INDEX idx_user_subscriptions_church_id ON user_subscriptions (church_id);

CREATE INDEX idx_streaming_sessions_church_id ON streaming_sessions (church_id);

CREATE INDEX idx_active_listeners_session_id ON active_listeners (session_id);

CREATE INDEX idx_active_listeners_last_heartbeat ON active_listeners (last_heartbeat);