-- Migration: 001_initial_schema.sql
-- VerbumDigital Web Radio - Initial Database Schema
-- Based on agreed schema with Svilen (Feb 2026)

BEGIN;

-- ============================================
-- HARDWARE
-- ============================================
CREATE TABLE machines (
    id SERIAL PRIMARY KEY,
    machine_id VARCHAR(50) UNIQUE NOT NULL, -- es: "SMIX-12345"
    activated BOOLEAN DEFAULT false,
    activation_code VARCHAR(20),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- CHURCHES
-- ============================================
CREATE TABLE churches (
    id SERIAL PRIMARY KEY,
    machine_id INTEGER UNIQUE REFERENCES machines (id),
    name VARCHAR(200) NOT NULL,
    logo_url VARCHAR(500),
    address TEXT,
    streaming_active BOOLEAN DEFAULT false, -- Real-time status
    current_session_id INTEGER, -- Populated later via FK
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- STREAMING CREDENTIALS (per church, permanent)
-- Generated by Admin on machine activation
-- Used by ST1 to identify the stream on Icecast
-- ============================================
CREATE TABLE streaming_credentials (
    id SERIAL PRIMARY KEY,
    church_id INTEGER UNIQUE REFERENCES churches (id) ON DELETE CASCADE,
    stream_id VARCHAR(100) UNIQUE NOT NULL, -- Encoded into Icecast URL
    stream_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- PRIESTS (can manage multiple churches)
-- ============================================
CREATE TABLE priests (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- PRIEST-CHURCH RELATIONSHIP (N:N)
-- ============================================
CREATE TABLE priest_churches (
    id SERIAL PRIMARY KEY,
    priest_id INTEGER REFERENCES priests (id) ON DELETE CASCADE,
    church_id INTEGER REFERENCES churches (id) ON DELETE CASCADE,
    role VARCHAR(20) DEFAULT 'owner', -- 'owner' or 'assistant'
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE (priest_id, church_id)
);

-- ============================================
-- USERS (fedeli)
-- ============================================
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- USER SUBSCRIPTIONS (with notification prefs)
-- ============================================
CREATE TABLE user_subscriptions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    church_id INTEGER REFERENCES churches (id) ON DELETE CASCADE,
    notifications_enabled BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE (user_id, church_id)
);

-- ============================================
-- ADMINS (internal use)
-- ============================================
CREATE TABLE admins (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- STREAMING SESSIONS (with statistics)
-- ============================================
CREATE TABLE streaming_sessions (
    id SERIAL PRIMARY KEY,
    church_id INTEGER REFERENCES churches (id),
    started_by_priest_id INTEGER REFERENCES priests (id),
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP,
    duration_seconds INTEGER,
    recording_url VARCHAR(500),
    max_listener_count INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Add FK from churches.current_session_id to streaming_sessions
ALTER TABLE churches
ADD CONSTRAINT fk_churches_current_session FOREIGN KEY (current_session_id) REFERENCES streaming_sessions (id);

-- ============================================
-- ACTIVE LISTENERS (real-time tracking)
-- Tracked via User PWA connections (as agreed with Svilen)
-- ============================================
CREATE TABLE active_listeners (
    id SERIAL PRIMARY KEY,
    session_id INTEGER REFERENCES streaming_sessions (id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (id),
    connected_at TIMESTAMP DEFAULT NOW(),
    last_heartbeat TIMESTAMP DEFAULT NOW()
);

-- ============================================
-- INDEXES for common queries
-- ============================================
CREATE INDEX idx_churches_streaming_active ON churches (streaming_active);

CREATE INDEX idx_churches_machine_id ON churches (machine_id);

CREATE INDEX idx_streaming_credentials_stream_id ON streaming_credentials (stream_id);

CREATE INDEX idx_priest_churches_priest_id ON priest_churches (priest_id);

CREATE INDEX idx_priest_churches_church_id ON priest_churches (church_id);

CREATE INDEX idx_user_subscriptions_user_id ON user_subscriptions (user_id);

CREATE INDEX idx_user_subscriptions_church_id ON user_subscriptions (church_id);

CREATE INDEX idx_streaming_sessions_church_id ON streaming_sessions (church_id);

CREATE INDEX idx_active_listeners_session_id ON active_listeners (session_id);

CREATE INDEX idx_active_listeners_last_heartbeat ON active_listeners (last_heartbeat);

COMMIT;